---
# tasks file for deploy-hello-web
- name: Create temp directory
  become: true
  ansible.builtin.file:
    path: /tmp/hello-web
    state: directory

- name: Download and extract application binary
  become: true
  get_url: 
    url: "https://github.com/bxffour/terrafrom-webserver/releases/download/{{ hello_web_version }}/hello-web.tar.xz"
    dest: "/tmp/hello-web/hello-web.tar.xz"

- name: Extract hello-web tarball
  become: true
  command: "tar xJf /tmp/hello-web/hello-web.tar.xz -C /tmp/hello-web"

- name: Copy hello-web binary
  become: true
  copy:
    src: "/tmp/hello-web/hello-web"
    dest: "/usr/bin/hello-web"
    mode: "0755"

- name: Create system user
  become: true
  user:
    name: "shtanwebapp"
    comment: "Hello Web Application User"
    system: yes
    shell: "/bin/false"
    home: "/opt/hello-web"

- name: Create hello-web directory
  become: true
  file:
    path: "/opt/hello-web"
    state: directory
    owner: "shtanwebapp"
    group: "shtanwebapp"
    mode: "0700"

- name: Create envfile template
  become: true
  template:
    src: "helloweb.env.j2"
    dest: "/opt/hello-web/hello-web.env"
    owner: "shtanwebapp"
    group: "shtanwebapp"
    mode: "0600"

- name: Copy hello-web service file
  become: true
  copy:
    src: "/tmp/hello-web/hello-web.service"
    dest: "/etc/systemd/system/hello-web.service"
    mode: "0644"

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Start and enable hello-web service
  become: true
  systemd:
    name: hello-web.service
    state: started
    enabled: yes
