---
# tasks file for deploy-hello-web
- name: Create temp directory
  become: true
  ansible.builtin.file:
    path: /tmp/hello-web
    state: directory

- name: Download and extract application binary
  become: true
  ansible.builtin.get_url: 
    url: "https://github.com/bxffour/terrafrom-webserver/releases/download/{{ app_version }}/hello-web.tar.xz"
    dest: "/tmp/hello-web/hello-web.tar.xz"

- name: Extract hello-web tarball
  become: true
  ansible.builtin.unarchive:
    src: /tmp/hello-web/hello-web.tar.xz
    dest: /tmp/hello-web
    remote_src: yes

- name: Copy hello-web binary
  become: true
  ansible.builtin.copy:
    src: "/tmp/hello-web/hello-web"
    dest: "/usr/bin/hello-web"
    mode: "0755"
    remote_src: true

- name: Create system user
  become: true
  ansible.builtin.user:
    name: "shtanwebapp"
    shell: "/sbin/nologin"
    home: "/opt/hello-web"
    groups: sudo

- name: Create hello-web directory
  become: true
  ansible.builtin.file:
    path: "/opt/hello-web"
    state: directory
    owner: "shtanwebapp"
    group: "shtanwebapp"
    mode: "0700"

- name: Create envfile template
  become: true
  ansible.builtin.template:
    src: "helloweb.env.j2"
    dest: "/opt/hello-web/helloweb.env"
    owner: "shtanwebapp"
    group: "shtanwebapp"
    mode: "0600"

- name: Copy hello-web service file
  become: true
  ansible.builtin.copy:
    src: "/tmp/hello-web/hello-web.service"
    dest: "/etc/systemd/system/hello-web.service"
    mode: "0644"
    remote_src: true

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable hello-web service
  become: true
  ansible.builtin.systemd:
    name: hello-web.service
    state: started
    enabled: yes
